Ready homework 5
zovag/Angular2 pull request #1
Opened 2017-05-07 07:55 UTC by zovag

Homework is ready

2017-05-08 17:47 UTC, ghost requested changes
реквест не полный выполните `git checkout HW-5 && git rebase master`

2017-05-08 17:47 UTC, captainkovalsky commented on src/app/app.component.html
>  <!--<app-main-board></app-main-board>-->
коменты не нужно хранить так как вся история и так в гите есть

2017-05-08 18:53 UTC, zovag commented on src/app/app.component.html
>  <!--<app-main-board></app-main-board>-->
Сделала git checkout HW-5 && git rebase master

2017-05-08 19:09 UTC, ghost requested changes
https://github.com/zovag/Angular2/blob/master/src/app/film-card/film-card.service.ts#L12

при ввводе несуществующего фильма вернется обьект у которого нету поля Search соответсвенно в компоненту вернется {} что произведет к ошибкам в консоли

2017-05-08 19:34 UTC, zovag commented
А что надо сделать чтобы эти ошибки не сыпались в консоль, проверку на ошибку и выводить сообщение об ошибке на экран?

2017-05-10 20:08 UTC, captainkovalsky commented
@zovag  Сюда https://github.com/zovag/Angular2/blob/master/src/app/film-card/film-card.component.html#L8 можно вставить `<div *ngIf="filmList.length === 0">Фильмы не найдены</div>`

2017-05-10 20:23 UTC, zovag commented
Сделала. Спасибо за подсказку!

2017-05-25 20:24 UTC, ghost approved these changes

2017-05-26 18:05 UTC, merged